repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: resize-logos
        name: Resize Logos
        entry: scripts/resize_images.py
        language: python
        language_version: python3
        additional_dependencies: [pillow, pyprojroot]
        types: [png]
        files: logo\.png$
        pass_filenames: false
