trigger:
- master 

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH.

- script: conda env create -f environment.yml
  displayName: Create environment.

- script: |
    conda activate website
    pip install git+https://github.com/lektor/lektor.git
  displayName: Install latest Lektor.
  
- script: |
    conda activate website
    lektor build
  displayName: Build website.

- task: DownloadSecureFile@1
  inputs:
    secureFile: azure_rsa
  displayName: Get deploy key.

- script: |
    mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  displayName: Setup SSH.

- script: |
    lektor deploy gh_ssh
  displayName: Deploy website.
