trigger:
- master 

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: conda env create -f environment.yml
  displayName: Create environment

- script: pip install git+https://github.com/lektor/lektor.git
  displayName: Install latest Lektor
  
- script: lektor build
  displayName: Build website
