trigger:
- master 

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: pip install git+https://github.com/lektor/lektor.git
  displayName: Install Lektor
  
- script: lektor build
  displayName: Build website
