name: website
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - lektor>=3.2.0
  - flask
  - requests
  - jinja2
  - mamba>=0.7.12
  - pre-commit
  - ipykernel
  - jupyterlab
  - fastapi
  - uvicorn
  - python-multipart
  - nbconvert>=7.16.4
  - werkzeug>=2.3.8
  - tqdm
  - panel
  - pip:
      - llamabot>=0.4.6
