name: website
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - lektor>=3.2.0
  # - mamba>=0.7.12
  - pre-commit
  # - ipykernel
  # - jupyterlab
  - nbconvert
  # - werkzeug>=2.3.8
  - tqdm
  - panel
  - pip:
      - llamabot>=0.4.6
